stages:
  - tagChecking
  - build
  - test
  - sonarqube
  - deploy

tag-checker:
  stage: tagChecking
  script:
    - python3 tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - ./gradlew test
    - ls ./build/jacoco
  artifacts:
    paths:
      - build/jacoco/test-report.xml

sonarqube-report:
  stage: sonarqube
  script:
    - ./gradlew sonarqube

# builds all branches, except dev and main
branch-build:
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs
  except:
    - tags
    - main
    - dev

deploy-staging:
  stage: deploy
  script:
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/staging/ || true
    - mkdir /home/gitlab-runner/staging/
    - cp -r ./build/libs /home/gitlab-runner/staging
    - cp runner-scripts/staging.sh /home/gitlab-runner/staging.sh
    - chmod u+x /home/gitlab-runner/staging.sh
    - echo "export DB_PASSWORD=${DB_PASSWORD}" > /home/gitlab-runner/staging/.env
    - echo "export DB_USERNAME=${DB_USERNAME}" >> /home/gitlab-runner/staging/.env
    - echo "export EMAIL_PASSWORD=${EMAIL_PASSWORD}" >> /home/gitlab-runner/staging/.env
    - echo "export EMAIL_USERNAME=${EMAIL_USERNAME}" >> /home/gitlab-runner/staging/.env
    - echo "export EMAIL_PORT=${EMAIL_PORT}" >> /home/gitlab-runner/staging/.env
    - echo "export API_KEY=${API_KEY}" >> /home/gitlab-runner/staging/.env
    - echo "export OPENAI_API_KEY=${OPENAI_API_KEY}" >> /home/gitlab-runner/staging/.env
    - sudo systemctl restart staging

  artifacts:
    paths:
      - build/libs
  only:
    - dev

deploy-production:
  stage: deploy
  script:
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/production/ || true
    - mkdir /home/gitlab-runner/production/
    - cp -r ./build/libs /home/gitlab-runner/production
    - cp runner-scripts/production.sh /home/gitlab-runner/production.sh
    - chmod u+x /home/gitlab-runner/production.sh
    - echo "export DB_PASSWORD=${DB_PASSWORD}" > /home/gitlab-runner/production/.env
    - echo "export DB_USERNAME=${DB_USERNAME}" >> /home/gitlab-runner/production/.env
    - echo "export EMAIL_PASSWORD=${EMAIL_PASSWORD}" >> /home/gitlab-runner/production/.env
    - echo "export EMAIL_USERNAME=${EMAIL_USERNAME}" >> /home/gitlab-runner/production/.env
    - echo "export EMAIL_PORT=${EMAIL_PORT}" >> /home/gitlab-runner/production/.env
    - echo "export API_KEY=${API_KEY}" >> /home/gitlab-runner/production/.env
    - echo "export OPENAI_API_KEY=${OPENAI_API_KEY}" >> /home/gitlab-runner/production/.env
    - sudo systemctl restart production
  artifacts:
    paths:
      - build/libs
  only:
    - tags
