SET MODE MySQL;
-- Setup a test user with password Password1234!
INSERT INTO garden_user(date_of_birth, email, fName, lName, password, picture_path) VALUES ('2003-08-19', 'test@example.com', 'Test', 'User', '$2a$10$Ra2OyNaklSi.YcfvGPuN9urUjCT17A9Kmu57zYftXe0ydZpEqbHg.', '/images/default_pic.jpg');
INSERT INTO garden_user(date_of_birth, email, fName, lName, password, picture_path) VALUES ('2003-08-19', 'user@example.com', 'User', 'Test', '$2a$10$Ra2OyNaklSi.YcfvGPuN9urUjCT17A9Kmu57zYftXe0ydZpEqbHg.', '/images/default_pic.jpg');
INSERT INTO garden_user(date_of_birth, email, fName, lName, password, picture_path) VALUES ('2003-08-19', 'big@example.com', 'Big', 'User', '$2a$10$Ra2OyNaklSi.YcfvGPuN9urUjCT17A9Kmu57zYftXe0ydZpEqbHg.', '/images/default_pic.jpg');

-- I Hanan Used a LLM to update this file on 30/04/2024 the following inserts were generated



-- Create a garden the Hamilton Garden (id = 1)
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('The Hamilton Gardens', '21 Hungerford Crescent', 'Hamilton East', 'Hamilton', '3216', 'New Zealand', -37.8057, 175.3049, 72000, 'Very cool garden', 1, true);
-- add some plants to the Hamilton Garden
INSERT INTO plant (name, plant_count, description, planted_on_date, picture_path, garden_id) VALUES ('Rose Bush', 200, 'Fragrant, colorful garden flower.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Lavender', 50, 'Aromatic purple herb.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Sunflower ', 100, 'Tall with large yellow flowers.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Fern', 1150, 'Lush, green leafy plant.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Tomato', 40, 'Edible red fruiting plant.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Basil', 30, 'Aromatic herb used in cooking.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Cactus', 20, 'Hardy desert plant with spines.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Daisy', 45, 'Small white flowers with a yellow center.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Lemon Tree', 90, 'Produces yellow citrus fruits.', null, '/images/defaultPlantPic.png', 1),
                                                                                                    ('Lily', 60, 'Elegant flowers with various colors and patterns.', null, '/images/defaultPlantPic.png', 1);


-- Create a garden called the Christchurch Botanic Gardens (id = 2)
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('The Christchurch Botanic Gardens', 'Rolleston Avenue', 'Christchurch Central', 'Christchurch', '8013', 'New Zealand', -43.5307, 172.6232, 7000, '', 1, false);
-- add some plants to the Christchurch Botanic Gardens (all the plants in this garden ar very stinky! They are also terribly disorganized and have no plant counts)
INSERT INTO plant (name, description, picture_path, garden_id) VALUES ('Corpse Flower', 'The worlds smelliest flower.', '/images/defaultPlantPic.png', 2),
                                                                      ('Durian', 'The worlds smelliest fruit.', '/images/defaultPlantPic.png', 2),
                                                                      ('Stinkhorn', 'The worlds smelliest mushroom.', '/images/defaultPlantPic.png', 2),
                                                                      ('Voodoo Lily', 'The worlds smelliest lily.', '/images/defaultPlantPic.png', 2),
                                                                      ('Skunk Cabbage', 'The worlds smelliest cabbage.', '/images/defaultPlantPic.png', 2);

-- Create a garden called the Jack Erskine Foyer Garden Set (id = 3) this garden has no size
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, description, owner_id, is_public) VALUES ('The Jack Erskine Foyer Garden Set', 'University of Canterbury', 'Ilam', 'Christchurch', '8041', 'New Zealand', -43.5225, 172.5794, 'A cool garden', 1, false);
-- add some plants to the Jack Erskine Foyer Garden Set these are all house plants and there is at lease 3 of each kind
INSERT INTO plant (name, plant_count, description, picture_path, garden_id) VALUES ('Spider Plant', 3, 'A hardy house plant with long, thin leaves.', '/images/defaultPlantPic.png', 3),
                                                                                   ('Peace Lily', 3, 'A hardy house plant with large, white flowers.', '/images/defaultPlantPic.png', 3),
                                                                                   ('Aloe Vera', 3, 'A hardy house plant with thick, fleshy leaves.', '/images/defaultPlantPic.png', 3),
                                                                                   ('Snake Plant', 3, 'A hardy house plant with tall, thin leaves.', '/images/defaultPlantPic.png', 3),
                                                                                   ('Pothos', 3, 'A hardy house plant with heart-shaped leaves.', '/images/defaultPlantPic.png', 3);

-- Create a garden called User Test's Secret Garden (id = 4) This is for testing garden ownership and plant ownership
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('User Test''s Secret Garden', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'A very... interesting... garden', 2, false);
-- add some plants to User Test's Secret Garden these should all be plants that are illegal to own in New Zealand This user has a LARGE QUANTITY of each plant
INSERT INTO plant (name, plant_count, description, picture_path, garden_id) VALUES ('Cannabis', 420, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Coca', 100000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Opium Poppy', 10000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Magic Mushrooms', 1000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Khat', 1000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Peyote', 1000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Salvia', 1000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Kratom', 1000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Ayahuasca', 1000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4),
                                                                                   ('Iboga', 1000, 'A psychoactive drug plant.', '/images/defaultPlantPic.png', 4);

INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 1', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 2', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 3', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 4', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 5', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 6', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 7', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 8', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 9', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 10', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 11', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 12', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 13', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 14', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 15', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 16', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 17', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 18', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 19', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 20', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 21', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 22', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 23', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 24', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 25', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 26', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 27', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 28', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 29', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 30', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 31', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 32', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 33', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 34', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 35', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 36', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 37', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 38', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 39', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 40', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 41', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 42', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 43', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 44', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 45', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 46', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 47', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 48', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 49', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 50', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 51', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 52', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 53', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 54', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 55', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 56', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 57', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 58', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 59', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 60', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 61', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 62', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 63', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 64', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 65', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 66', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 67', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 68', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 69', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 70', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 71', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 72', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 73', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 74', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 75', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 76', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 77', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 78', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 79', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 80', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 81', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 82', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 83', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 84', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 85', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 86', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 87', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 88', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 89', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 90', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 91', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 92', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 93', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 94', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 95', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 96', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 97', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 98', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 99', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);
INSERT INTO garden (name, address, suburb, city, postcode, country, latitude, longitude, size, description, owner_id, is_public) VALUES ('Big User Garden 100', '123 Fake Street', 'Fake Suburb', 'Fake City', '1234', 'Fake Country', null, null, 100, 'One of many gardens', 3, true);