INSERT INTO garden (name, location, size) VALUES ('GardenWith12Plants', 'Springfield', 10);
INSERT INTO garden (name, location, size) VALUES ('GardenWith10Plants', 'Springfield', 10);
INSERT INTO garden (name, location, size) VALUES ('TestGarden', 'TestLocation', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 2);
INSERT INTO garden (name, location, size) VALUES ('Woohoo', 'Yeah', 30.5);
INSERT INTO garden (name, location, size) VALUES ('The Hamilton Gardens', 'Hamilton, New Zealand', 540000);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Rose Bush', 200, 'Fragrant, colorful garden flower.', null, 5);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Lavender', 50, 'Aromatic purple herb.', null, 5);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Sunflower ', 100, 'Tall with large yellow flowers.', null, 5);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Fern', 1150, 'Lush, green leafy plant.', null, 5);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Tomato', 40, 'Edible red fruiting plant.', null, 5);
INSERT INTO garden (name, location, size) VALUES ('A1 .-''', 'A1 ,.-''', 123.456);
INSERT INTO garden (name, location, size) VALUES ('Unsized Garden', 'Unsized Garden', null);
INSERT INTO garden (name, location, size) VALUES ('Long name garden yappa yappa yappa yappa', 'Hmm', 1);
INSERT INTO garden (name, location, size) VALUES ('Longnamegardenyappayappayappayappa', 'Hmm', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);
INSERT INTO plant (name, plant_count, description, planted_on_date, garden_id) VALUES ('Plant', 1, 'Its green', '2023-01-01', 1);


